[package]
name = "webgl_test"
version = "0.1.0"
authors = ["z"]

[dependencies]
lazy_static = ">=1.0.2"
nalgebra = ">=0.16.0"
pcg_rand = ">=0.8.0"
rand = "^0.4.2"
wasm-bindgen = ">=0.2.14"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
debug = true  # For wasm-bindgen
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
