[package]
name = "webgl_test"
version = "0.1.0"
authors = ["z"]

[dependencies]
nalgebra = ">=0.16.0"
wasm-bindgen = ">=0.2.14"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
debug = true  # For wasm-bindgen
rpath = false
lto = false  # For wasm-bindgen
debug-assertions = false
codegen-units = 1
panic = "abort"
incremental = false
overflow-checks = false
